# instruments.py
# Autogenerated notfi
alarms = {
    "index": 0,
    "notes": [
        "alarm 1"
    ]
}
drumkit = {
    "index": 1,
    "notes": [
        "kick"
    ]
}

instruments = {
    "programmable-speaker": {
        "alarms": alarms,
        0:        alarms,
        "drumkit": drumkit,
        1: drumkit
    }
}