name: Environment CI
on: [pull_request, release, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - 'factorio+'
          - 'issue_182'
          - 'issue_197'
          - 'issue_199'
          - 'krastorio2'
          - 'pyanodons'
          - 'ultracube'
          - 'warptorio2'
          - 'yuoki'
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
        path: factorio-draftsman
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install Draftsman
      run: pip install .
      working-directory: ./factorio-draftsman
    - name: Checkout `factorio-mod-downloader`
      uses: actions/checkout@v5
      with:
        repository: redruin1/factorio-mod-downloader
        ref: develop
        path: factorio-mod-downloader
    - name: Install poetry
      uses: snok/install-poetry@v1
    - name: Install deps for `factorio-mod-downloader`
      run: poetry install
      working-directory: ./factorio-mod-downloader
    - name: Install Factorio mods
      run: |
        poetry run factorio-mod-downloader \
          --headless \
          --file "../factorio-draftsman/.github/workflows/environments/${{ matrix.environment }}/mod-sources.txt" \
          --destination "../factorio-draftsman/.github/workflows/environments/${{ matrix.environment }}" \
          --ignore-overwrite
      working-directory: ./factorio-mod-downloader
    - name: Run `draftsman update`
      run: |
        tree .github/workflows/environments
        draftsman -v --mods-path ".github/workflows/environments/${{ matrix.environment }}" update
      working-directory: ./factorio-draftsman
