name: Push CI
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.10.4'
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.10.4
    - name: Run tests and generate coverage report
      run: |
        pip install --group test
        pip install -e .
        coverage run
        coverage xml