name: Push CI
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install UV
      uses: astral-sh/setup-uv@v6
    - name: Install Just with pipx
      uses: threeal/pipx-install-action@v1
      with:
        packages: rust-just
    - name: Create venv and Install Draftsman
      run: |
        uv venv --python 3.13
        uv pip install --group test
        uv pip install -e .
    - name: Run tests
      run: |
        pwd
        ls
        just test
    - name: Combine and make XML
      run: |
        coverage combine
        coverage xml